import type { VehicleOSResaleReportV1 } from "./build-resale-report.js";

const formatMileage = (mileage: number): string => `${mileage.toLocaleString()} mi`;

export const formatResaleReportMarkdown = (report: VehicleOSResaleReportV1): string => {
  const { vehicle, summary } = report;
  const vehicleLabel = `${vehicle.year} ${vehicle.make} ${vehicle.model}`;
  const lines: string[] = [
    `# Vehicle OS resale evidence report`,
    ``,
    `**Vehicle:** ${vehicleLabel}${vehicle.trim ? ` ${vehicle.trim}` : ""}`,
    `**VIN:** ${vehicle.vin}`,
    `**Current mileage:** ${formatMileage(vehicle.currentMileage)}`,
    `**Exported:** ${report.exportedAt}`,
    ``,
    `## Summary`,
    ``,
    `- **Recorded services:** ${summary.serviceCount}`,
    `- **Evidence artifacts:** ${summary.evidenceCount}`,
  ];

  if (summary.earliestServiceDate && summary.latestServiceDate) {
    lines.push(
      `- **Service window:** ${summary.earliestServiceDate} → ${summary.latestServiceDate}`,
    );
  }

  if (summary.lowestRecordedMileage !== undefined && summary.highestRecordedMileage !== undefined) {
    lines.push(
      `- **Recorded mileage range:** ${formatMileage(summary.lowestRecordedMileage)} → ${formatMileage(summary.highestRecordedMileage)}`,
    );
  }

  lines.push(``, `## Maintenance timeline`, ``);

  if (report.timeline.length === 0) {
    lines.push(`No services recorded yet.`);
  } else {
    for (const entry of report.timeline) {
      lines.push(
        `### ${entry.serviceDate} · ${formatMileage(entry.mileage)} · ${entry.shop}`,
        ``,
        `- **Total:** ${entry.total}`,
        `- **Work:** ${entry.lineItems.join("; ")}`,
      );
      if (entry.evidenceIds.length > 0) {
        lines.push(`- **Evidence IDs:** ${entry.evidenceIds.join(", ")}`);
      }
      lines.push(``);
    }
  }

  lines.push(`## Evidence vault`, ``);

  if (report.evidenceVault.length === 0) {
    lines.push(`No immutable evidence artifacts stored.`);
  } else {
    for (const artifact of report.evidenceVault) {
      lines.push(
        `- **${artifact.documentId}** · ${artifact.channel} · ingested ${artifact.ingestedAt}`,
      );
    }
  }

  if (report.quoteAnalyses.length > 0) {
    lines.push(``, `## Quote checks`, ``);
    for (const analysis of report.quoteAnalyses) {
      lines.push(`### ${analysis.analyzedAt}${analysis.shop ? ` · ${analysis.shop}` : ""}`, ``);
      lines.push(analysis.summary, ``);
      for (const line of analysis.lines) {
        lines.push(
          `- ${line.description}: $${line.quotedAmount.toFixed(2)} (${line.verdict}) — ${line.reason}`,
        );
      }
      lines.push(``);
    }
  }

  lines.push(
    `---`,
    ``,
    `Generated by Vehicle OS · structured export ${report.kind}`,
  );

  return lines.join("\n");
};
